use_frameworks!

platform :ios, '9.0'

target 'LSJHAlertController_Example' do
  pod 'LSJHAlertController', :path => '../'

  target 'LSJHAlertController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
